# Presentación Julia 1

In [1]:
using Dates # para manejar fechas
Dates.format(now(),"E: dd U yyyy, H:M:S:s")

"Tuesday: 17 November 2020, 17:17:1:907"

## ¿Qué es Julia?

Es un lenguaje de programación para computación técnica de alto nivel, dinámico y de alto desempeño, con una sintaxis familiar para usuarios de otros ambientes de computación técnica.

Julia es un lenguaje de programación para todo propósito de fuente abierta y gratis. La fuente se encuentra en `Github` y puede verse [aquí](https://github.com/JuliaLang/julia). Para descargar `Julia` vaya [aquí](https://julialang.org). Dé clic en `downloadXXX` escoja el sistema operativo de su equipo y descargue el software que le corresponde. Se ejecuta en la forma usual y se accdede a la consola de julia.

![alt text](consola.png "Consola de julia")

In [1]:
versioninfo(verbose=true) # verbose=true da más detalles

Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  uname: Darwin 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64 i386
  CPU: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz: 
              speed         user         nice          sys         idle          irq
       #1  2300 MHz      60099 s          0 s      51592 s     334689 s          0 s
       #2  2300 MHz      21028 s          0 s      14232 s     411093 s          0 s
       #3  2300 MHz      58428 s          0 s      33720 s     354206 s          0 s
       #4  2300 MHz      19186 s          0 s      11444 s     415723 s          0 s
       
  Memory: 8.0 GB (390.859375 MB free)
  Uptime: 91059.0 sec
  Load Avg:  1.603515625  1.57080078125  1.5517578125
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  XPC_FLAGS = 0x0
  PATH = /Applications/Julia-1.5.app/Contents/Re

Para conocer el directorio de trabajo utilizar la función `pwd()` y para. cambiarlo usar `cd()`.

In [2]:
?cd

search: cd Cdouble gcd gcdx secd asecd cld Cmd codeunit codeunits codepoint



```
cd(dir::AbstractString=homedir())
```

Set the current working directory.

# Examples

```julia-repl
julia> cd("/home/JuliaUser/Projects/julia")

julia> pwd()
"/home/JuliaUser/Projects/julia"

julia> cd()

julia> pwd()
"/home/JuliaUser"
```

---

```
cd(f::Function, dir::AbstractString=homedir())
```

Temporarily change the current working directory to `dir`, apply function `f` and finally return to the original directory.

# Examples

```julia-repl
julia> pwd()
"/home/JuliaUser"

julia> cd(readdir, "/home/JuliaUser/Projects/julia")
34-element Array{String,1}:
 ".circleci"
 ".freebsdci.sh"
 ".git"
 ".gitattributes"
 ".github"
 ⋮
 "test"
 "ui"
 "usr"
 "usr-staging"

julia> pwd()
"/home/JuliaUser"
```


In [3]:
pwd() # dirección del directorio de trabajo

"/Users/carloslesmes/Dropbox/JULIADIP"

In [6]:
readdir()

22-element Array{String,1}:
 ".DS_Store"
 ".ipynb_checkpoints"
 "09 - Expdistribution.ipynb.txt"
 "09 - Exponential distribution.ipynb.txt"
 "Metro.RData"
 "Pluto2.jl"
 "consola.png"
 "covid.csv"
 "df1.RData"
 "julia1.ipynb"
 "julia2.ipynb"
 "julia3.ipynb"
 "julia4.ipynb"
 "julia5.ipynb"
 "metro.jld"
 "pyjul.Rmd"
 "pyjul.html"
 "pyton_en_R.Rmd"
 "pyton_en_R.html"
 "test.png"
 "tipos.png"
 "youtubepart.html"

# Variables

Una variable en julia es un nombre asociado a un valor. La asignación se hace con "=". No se usa "<-" como en R. Por ejemplo.

In [ ]:
x = 5

In [ ]:
println(x)

Se puede operar y reasignar:

In [ ]:
x+3

In [ ]:
x = "Buenos días"

Julia es sensible a las mayúsculas..

In [ ]:
X 

Se pueden hacer entradas Unicode vea [aquí](https://docs.julialang.org/en/v1/manual/unicode-input/)

In [ ]:
🚗 = 8
🚗 + 1

Los nombres pueden ser largos...

In [ ]:
EstaVariableEsLarga = 2.0

La consola de julia es interactiva y trabaja con el ciclo `REPL`: read, evaluate, print loop, es decir toma las entradas individuales del usuario, las evalúa y devuelve el resultado. En este `REPL` se puede escribir símbolos LaTeX con la diagonal `\`y luego el tabulador `tab`.Vea [REPL](https://docs.julialang.org/en/v1/stdlib/REPL/).

In [ ]:
α = 5.4
α + 1

In [ ]:
ans

Las variables deben empezar con una letra (A-Z o a-z), guión bajo. Los caracteres siguientes pueden ser dígitos(0-9). No se permiten para nombres de variables algunos nombres como:

In [ ]:
else = 3

In [ ]:
try = "si"

In [ ]:
varinfo()

In [ ]:
dump(varinfo())

## Convenciones de estilo

Estas convenciones han mostrado ser bastante útiles:

1. Nombres de las variables en minúsculas
2. Separación de palabras con "_".
3. Los nombres de las funciones y de las macros van en minúscula sin "_".
4. Las funciones que afectan los argumentos llevan "!".

Los enteros y los valores de punto-flotante son básicos en la aritmética y los cálculos. Por ejemplo 1 es un entero y 1.0 es un valor de punto flotante.

In [ ]:
1.0

In [ ]:
1.

In [ ]:
.5

In [ ]:
1e10

## Algunos valores especiales

In [ ]:
1/Inf

In [ ]:
1/0

In [ ]:
-4/0

In [ ]:
0/0

In [ ]:
900 + Inf

In [ ]:
900 - Inf

In [ ]:
Inf + Inf

In [ ]:
Inf - Inf

In [ ]:
Inf * Inf

In [ ]:
Inf / Inf

In [ ]:
0 * Inf

El modelo de números reales: distancia entre dos reales adyacentes conocida como el epsilon de la máquina:`eps()` da la distancia entre 1.0 y el siguiente real representable.

In [ ]:
eps()

In [ ]:
eps(0.0)

In [ ]:
eps(100.)

In [ ]:
eps(DateTime)

La distancia entre dos punto-flotantes representables no es constante es pequeña para valores pequeños y más grande para valores más grandes. Hay más densidad alrededor de cero. 

## Precisión aritmética arbitraria

In [1]:
factorial(100)

LoadError: OverflowError: 100 is too large to look up in the table; consider using `factorial(big(100))` instead

In [2]:
factorial(big(100))

93326215443944152681699238856266700490715968264381621468592963895217599993229915608941463976156518286253697920827223758251185210916864000000000000000000000000

In [ ]:
factorial(big(1000000))

In [ ]:
@elapsed factorial(big(1000000))

In [ ]:
length(string(factorial(big(1000000))))

## Coeficientes numéricos

Para hacer más cómoda la escritura de expresiones julia permite que una variable sea precedida por un número implicando multiplicación:

In [ ]:
x = 5
3.0x^3 - 4x + 1

In [ ]:
2^2x

In [ ]:
(x-1)x

In [ ]:
(x-1)(x+1)

## Aritmética

In [ ]:
+1

In [ ]:
1+2

In [ ]:
1+2+3

In [ ]:
3-4

In [ ]:
2+5/6

In [ ]:
y = 500
y += 1 # y = y +1

In [ ]:
y /= 2 # y = y/2

In [ ]:
y ^= 0.5  # y = y^0.5

## Comparaciones

    Operaciones típicas de comparación: >, <, ==, !=, >=, >=

In [ ]:
2 == 2

In [ ]:
2 == 3

In [ ]:
2 == 2.0

In [ ]:
-1 > 1

In [ ]:
4 ≤ 7

In [ ]:
NaN == NaN

In [ ]:
NaN != NaN

In [ ]:
isequal(-0.0,0.0)

In [ ]:
isinf(1/0)

In [ ]:
isnan(Inf/Inf)

In [ ]:
NaN > Inf

In [ ]:
3 < 7 > 2 != 5

## Algunas funciones elementales

In [ ]:
pi

In [ ]:
round(pi)

In [ ]:
floor(pi)

In [ ]:
ceil(pi)

In [ ]:
trunc(4.5)

In [ ]:
7 % 3

In [ ]:
gcd(50,30)

In [ ]:
lcm(5,7,9)

In [ ]:
sqrt(2)

In [ ]:
cbrt(512)

In [ ]:
log(2)

In [ ]:
sin(pi/4)

In [ ]:
sind(45)

In [ ]:
a=1:15
filter(isodd,a)

## Números complejos y racionales

In [ ]:
2 + 3im

In [ ]:
(1 - im)*(2 + 3im)

In [ ]:
(2 + im)/(1- im)

In [ ]:
(2- 3im)^2

In [ ]:
3(1- 2im)

In [ ]:
im ^2

In [ ]:
real(2 - 4im)

In [ ]:
imag(2 - 4im)

In [ ]:
abs(2 - 4im)

In [ ]:
sqrt(im)

In [ ]:
cos(1 + im)

In [ ]:
exp(pi*im)

In [ ]:
a = 1 ; b = 2 ; a + b*im

In [ ]:
z = 3 + 4im

In [ ]:
z = complex(3,4)

In [ ]:
2//5

In [ ]:
-3//6

In [ ]:
1//4 + 1//5

In [ ]:
2//3 == 6//9

In [ ]:
num(4//5)

In [ ]:
numerator(4//5)

In [ ]:
denominator(4//7)

In [ ]:
7//8 / 4//9

In [ ]:
float(3//4)

In [ ]:
3//5 + 1

In [ ]:
1//9*(2 - 3im)

In [ ]:
1//3 -1/3

In [ ]:
rationalize(0.25)

In [ ]:
rationalize(0.3333333333333333333333)

## Strings

Los strings son sucesiones finitas de caracteres.

In [ ]:
'g'

In [ ]:
typeof(ans)

In [ ]:
str1 = "Buenos días"

In [ ]:
str1[1]

In [ ]:
str1[5]

In [ ]:
str1[end]

In [ ]:
str1[end-1]

In [ ]:
str1[4:6]

In [ ]:
s = "\u2200 x \u2203 y"

In [ ]:
uno = "uno1"

In [ ]:
dos = "dos2"

In [ ]:
uno * dos

In [ ]:
" 1 +2 = $(1+2)"

In [ ]:
promote(3//4,0.86)

In [ ]:
convert(Rational,3)

### Pedir ayuda

Con `?`y la función de la cual se quiere tener información.

In [ ]:
?sqrt

### Entrar al terminal

Con `;`se entra a la línea de comandos.

In [ ]:
;cal 2020

In [ ]:
;ls

En el siguiente video [day](https://youtu.be/JNvMs0j3a4E?t=600) se puede ver ...

# Diccionarios

Se puede crear un diccionario simple con la siguiente sintaxis:

In [21]:
dic=Dict("a" => 3, "b" => 4, "c" => 5)

Dict{String,Int64} with 3 entries:
  "c" => 5
  "b" => 4
  "a" => 3

"a", "b" y "c" se llaman **llaves** y 3,4, y 5 **valores**. Un diccionario asocia llaves con valores. El operador `=>`es la función `Pair()`. No puede haber dos llaves con el mismo nombre.

In [22]:
Pair("ocho",8)

"ocho" => 8

In [23]:
keys(dic)

Base.KeySet for a Dict{String,Int64} with 3 entries. Keys:
  "c"
  "b"
  "a"

In [24]:
values(dic)

Base.ValueIterator for a Dict{String,Int64} with 3 entries. Values:
  5
  4
  3

In [25]:
dic["a"]

3

In [26]:
haskey(dic,"c")

true

In [27]:
in(("c" => 5), dic)

true

In [28]:
dic["e"]=8;
dic

Dict{String,Int64} with 4 entries:
  "c" => 5
  "e" => 8
  "b" => 4
  "a" => 3

Se pueden crear diccionarios vacíos.

In [ ]:
DicV=Dict()

Un ejemplo del paquete `PeriodicTable`.

In [ ]:
using PeriodicTable

In [ ]:
elements

In [ ]:
Dic2=elements.bysymbol

In [ ]:
Dic2[:Og]

# Conjuntos

Un conjunto es una colección de elementos no repetidos. El orden de los lementos no es importante.

In [29]:
colores=Set(["amarillo","azul","rojo"])

Set{String} with 3 elements:
  "amarillo"
  "rojo"
  "azul"

In [30]:
push!(colores,"verde")

Set{String} with 4 elements:
  "verde"
  "amarillo"
  "rojo"
  "azul"

In [31]:
in("azul",colores)

true

In [32]:
arcoiris = Set(["rojo","naranja","amarillo","verde","azul","indigo","violeta"])

Set{String} with 7 elements:
  "verde"
  "indigo"
  "amarillo"
  "naranja"
  "rojo"
  "violeta"
  "azul"

In [33]:
union(colores,arcoiris)

Set{String} with 7 elements:
  "verde"
  "indigo"
  "amarillo"
  "naranja"
  "rojo"
  "violeta"
  "azul"

In [34]:
intersect(colores,arcoiris)

Set{String} with 4 elements:
  "verde"
  "amarillo"
  "rojo"
  "azul"

In [35]:
setdiff(arcoiris,colores)

Set{String} with 3 elements:
  "indigo"
  "naranja"
  "violeta"

Las operaciones entre conjuntos funcionan en diccionarios:

In [36]:
d1=Dict(1 => "uno", 2 => "dos")

Dict{Int64,String} with 2 entries:
  2 => "dos"
  1 => "uno"

In [37]:
d2=Dict(2 => "dos", 3 => "tres", 4 => "cuatro")

Dict{Int64,String} with 3 entries:
  4 => "cuatro"
  2 => "dos"
  3 => "tres"

In [38]:
union(d1,d2)

4-element Array{Pair{Int64,String},1}:
 2 => "dos"
 1 => "uno"
 4 => "cuatro"
 3 => "tres"

In [39]:
intersect(d1,d2)

1-element Array{Pair{Int64,String},1}:
 2 => "dos"

In [40]:
setdiff(d2,d1)

2-element Array{Pair{Int64,String},1}:
 4 => "cuatro"
 3 => "tres"

# Usando pipes (encadenamiento)

El encadenamiento permite componer funciones de forma compacta y de fácil lectura. Evita almacenar resultados intermedios. Con el operador `|>` el código a la izquierda es el argumento del código a la derecha.

In [ ]:
sin(π/4)

In [ ]:
π/4 |> sin

In [42]:
a=3
g1(x)=x+4
g2(x)=x/2
a |> g1 |> g2 |> println

3.5


In [43]:
println(g2(g1(a)))

3.5


In [47]:
j(x,y) = x + sum(y)
[4,5,6] |> (y -> j(4,y))

19

El paquete `Pipe` con la macro `@pipe`permite hacer encadenamientos con funcione que tienen varios argumentos.

In [48]:
using Pipe

# Expresiones

Para crear expresiones se utiliza la sintaxis `:()`

In [ ]:
expr1=:(a+2*b)

In [ ]:
typeof(expr1)

In [ ]:
dump(expr1)

In [ ]:
w=1;
expr2=:($w+4)

In [ ]:
eval(expr2)

# Macros

Generalmente se aplican al código.

In [ ]:
using Statistics
@time mean(rand(1000000))

In [ ]:
@elapsed mean(rand(1000000))

In [ ]:
@which 3+4