# Julia 5 Paquetes

Un paquete es básicamente una colección de funciones. Julia contiene más de 5000 paqutes que están en el Registro General, [General registry](https://github.com/JuliaRegistries/General). afortunadamente, hay servicios que permiten navegar el ecosistema de paquetes, incluyendo:


## Paquete Pkg

Este modulo es el gestor de paquetes. En modo interactivo, en el REPL, entrar con`]`. [Pkg.jl](https://julialang.github.io/Pkg.jl/dev/).

In [1]:
] help

  Welcome to the Pkg REPL-mode. To return to the julia> prompt, either press
  backspace when the input line is empty or press Ctrl+C.

  Synopsis

  pkg> cmd [opts] [args]

  Multiple commands can be given on the same line by interleaving a ; between
  the commands. Some commands have an alias, indicated below.

  Commands

  activate: set the primary environment the package manager manipulates

  add: add packages to project

  build: run the build script for packages

  develop, dev: clone the full package repo locally for development

  free: undoes a pin, develop, or stops tracking a repo

  gc: garbage collect packages not used for a significant time

  generate: generate files for a new project

  help, ?: show this message

  instantiate: downloads all the dependencies for the project

  pin: pins the version of packages

  precompile: precompile all the project dependencies

  redo: redo the latest change to the active project

  remove, rm: remove packages from project or man

In [2]:
]add Pkg

┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Cu

In [3]:
using Pkg

# Random

In [4]:
using Random
display(varinfo(Random))

| name            |        size | summary             |
|:--------------- | -----------:|:------------------- |
| AbstractRNG     |   172 bytes | DataType            |
| MersenneTwister |   260 bytes | DataType            |
| Random          | 524.896 KiB | Module              |
| RandomDevice    |   188 bytes | DataType            |
| bitrand         |     0 bytes | typeof(bitrand)     |
| rand!           |     0 bytes | typeof(rand!)       |
| randcycle       |     0 bytes | typeof(randcycle)   |
| randcycle!      |     0 bytes | typeof(randcycle!)  |
| randexp         |     0 bytes | typeof(randexp)     |
| randexp!        |     0 bytes | typeof(randexp!)    |
| randn!          |     0 bytes | typeof(randn!)      |
| randperm        |     0 bytes | typeof(randperm)    |
| randperm!       |     0 bytes | typeof(randperm!)   |
| randstring      |     0 bytes | typeof(randstring)  |
| randsubseq      |     0 bytes | typeof(randsubseq)  |
| randsubseq!     |     0 bytes | typeof(randsubseq!) |
| shuffle         |     0 bytes | typeof(shuffle)     |
| shuffle!        |     0 bytes | typeof(shuffle!)    |


In [5]:
rand()

0.35980737165396093

In [6]:
rand(2,3)

2×3 Matrix{Float64}:
 0.637566  0.551248  0.60264
 0.50644   0.253563  0.136292

In [7]:
randn()

0.44050418156477456

In [8]:
randexp()

1.0418655698418091

In [9]:
randstring()

"aSZfWwR3"

In [10]:
randstring(5)

"1VJur"

In [11]:
rand(1:6)

2

In [12]:
rand(1:6,3)

3-element Vector{Int64}:
 6
 2
 2

In [13]:
rand(["uno","dos","tres"])

"tres"

In [14]:
Random.seed!(12349)

MersenneTwister(12349)

# DataFrames

# Paquetes para leer y escribir  archivos de datos

Los siguientes paquetes de Julia permiten traer archivos a Julia CSV, Parquet, SASLib, ReadStat, JSON, XLSX,PDFIO, 

## El paquete `RDatasets`

Este paquete nos da una sencilla forma de acceder a los conjuntos de datos de algunos paquetes de `R`. 

In [15]:
using RDatasets, DataFrames, CSV

In [16]:
RDatasets.packages()

34×2 DataFrame. Omitted printing of 1 columns
│ Row │ Package      │
│     │ String       │
├─────┼──────────────┤
│ 1   │ COUNT        │
│ 2   │ Ecdat        │
│ 3   │ HSAUR        │
│ 4   │ HistData     │
│ 5   │ ISLR         │
│ 6   │ KMsurv       │
│ 7   │ MASS         │
│ 8   │ SASmixed     │
│ 9   │ Zelig        │
│ 10  │ adehabitatLT │
⋮
│ 24  │ plyr         │
│ 25  │ pscl         │
│ 26  │ psych        │
│ 27  │ quantreg     │
│ 28  │ reshape2     │
│ 29  │ robustbase   │
│ 30  │ rpart        │
│ 31  │ sandwich     │
│ 32  │ sem          │
│ 33  │ survival     │
│ 34  │ vcd          │

In [17]:
RDatasets.datasets("ggplot2")

8×5 DataFrame. Omitted printing of 3 columns
│ Row │ Package │ Dataset      │
│     │ String  │ String       │
├─────┼─────────┼──────────────┤
│ 1   │ ggplot2 │ diamonds     │
│ 2   │ ggplot2 │ economics    │
│ 3   │ ggplot2 │ midwest      │
│ 4   │ ggplot2 │ movies       │
│ 5   │ ggplot2 │ mpg          │
│ 6   │ ggplot2 │ msleep       │
│ 7   │ ggplot2 │ presidential │
│ 8   │ ggplot2 │ seals        │

In [18]:
diamantes = dataset("ggplot2","diamonds")

53940×10 DataFrame. Omitted printing of 3 columns
│ Row   │ Carat   │ Cut       │ Color │ Clarity │ Depth   │ Table   │ Price │
│       │ Float64 │ Cat…      │ Cat…  │ Cat…    │ Float64 │ Float64 │ Int32 │
├───────┼─────────┼───────────┼───────┼─────────┼─────────┼─────────┼───────┤
│ 1     │ 0.23    │ Ideal     │ E     │ SI2     │ 61.5    │ 55.0    │ 326   │
│ 2     │ 0.21    │ Premium   │ E     │ SI1     │ 59.8    │ 61.0    │ 326   │
│ 3     │ 0.23    │ Good      │ E     │ VS1     │ 56.9    │ 65.0    │ 327   │
│ 4     │ 0.29    │ Premium   │ I     │ VS2     │ 62.4    │ 58.0    │ 334   │
│ 5     │ 0.31    │ Good      │ J     │ SI2     │ 63.3    │ 58.0    │ 335   │
│ 6     │ 0.24    │ Very Good │ J     │ VVS2    │ 62.8    │ 57.0    │ 336   │
│ 7     │ 0.24    │ Very Good │ I     │ VVS1    │ 62.3    │ 57.0    │ 336   │
│ 8     │ 0.26    │ Very Good │ H     │ SI1     │ 61.9    │ 55.0    │ 337   │
│ 9     │ 0.22    │ Fair      │ E     │ VS2     │ 65.1    │ 61.0    │ 337   │
│ 10    │ 0.23    │ Very Good │ H     │ VS1     │ 59.4    │ 61.0    │ 338   │
⋮
│ 53930 │ 0.71    │ Ideal     │ G     │ VS1     │ 61.4    │ 56.0    │ 2756  │
│ 53931 │ 0.71    │ Premium   │ E     │ SI1     │ 60.5    │ 55.0    │ 2756  │
│ 53932 │ 0.71    │ Premium   │ F     │ SI1     │ 59.8    │ 62.0    │ 2756  │
│ 53933 │ 0.7     │ Very Good │ E     │ VS2     │ 60.5    │ 59.0    │ 2757  │
│ 53934 │ 0.7     │ Very Good │ E     │ VS2     │ 61.2    │ 59.0    │ 2757  │
│ 53935 │ 0.72    │ Premium   │ D     │ SI1     │ 62.7    │ 59.0    │ 2757  │
│ 53936 │ 0.72    │ Ideal     │ D     │ SI1     │ 60.8    │ 57.0    │ 2757  │
│ 53937 │ 0.72    │ Good      │ D     │ SI1     │ 63.1    │ 55.0    │ 2757  │
│ 53938 │ 0.7     │ Very Good │ D     │ SI1     │ 62.8    │ 60.0    │ 2757  │
│ 53939 │ 0.86    │ Premium   │ H     │ SI2     │ 61.0    │ 58.0    │ 2757  │
│ 53940 │ 0.75    │ Ideal     │ D     │ SI2     │ 62.2    │ 55.0    │ 2757  │

In [19]:
using DataFrames, CSV, Statistics

In [20]:
url="https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"

"https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"

In [21]:
download(url,"covid.csv")

┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36
┌ Error: curl_easy_setopt: 48
└ @ Downloads.Curl /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36


"covid.csv"

In [22]:
begin
    datos_csv = CSV.File("covid.csv")
    datos = DataFrame(datos_csv)
end

280×727 DataFrame. Omitted printing of 724 columns
│ Row │ Province/State               │ Country/Region      │ Lat      │
│     │ Union{Missing, String}       │ String              │ Float64? │
├─────┼──────────────────────────────┼─────────────────────┼──────────┤
│ 1   │ missing                      │ Afghanistan         │ 33.9391  │
│ 2   │ missing                      │ Albania             │ 41.1533  │
│ 3   │ missing                      │ Algeria             │ 28.0339  │
│ 4   │ missing                      │ Andorra             │ 42.5063  │
│ 5   │ missing                      │ Angola              │ -11.2027 │
│ 6   │ missing                      │ Antigua and Barbuda │ 17.0608  │
│ 7   │ missing                      │ Argentina           │ -38.4161 │
│ 8   │ missing                      │ Armenia             │ 40.0691  │
│ 9   │ Australian Capital Territory │ Australia           │ -35.4735 │
│ 10  │ New South Wales              │ Australia           │ -33.8688 │
⋮
│ 270 │ Turks and Caicos Islands     │ United Kingdom      │ 21.694   │
│ 271 │ missing                      │ United Kingdom      │ 55.3781  │
│ 272 │ missing                      │ Uruguay             │ -32.5228 │
│ 273 │ missing                      │ Uzbekistan          │ 41.3775  │
│ 274 │ missing                      │ Vanuatu             │ -15.3767 │
│ 275 │ missing                      │ Venezuela           │ 6.4238   │
│ 276 │ missing                      │ Vietnam             │ 14.0583  │
│ 277 │ missing                      │ West Bank and Gaza  │ 31.9522  │
│ 278 │ missing                      │ Yemen               │ 15.5527  │
│ 279 │ missing                      │ Zambia              │ -13.1339 │
│ 280 │ missing                      │ Zimbabwe            │ -19.0154 │

In [23]:
names(datos)

727-element Vector{String}:
 "Province/State"
 "Country/Region"
 "Lat"
 "Long"
 "1/22/20"
 "1/23/20"
 "1/24/20"
 "1/25/20"
 "1/26/20"
 "1/27/20"
 "1/28/20"
 "1/29/20"
 "1/30/20"
 ⋮
 "1/2/22"
 "1/3/22"
 "1/4/22"
 "1/5/22"
 "1/6/22"
 "1/7/22"
 "1/8/22"
 "1/9/22"
 "1/10/22"
 "1/11/22"
 "1/12/22"
 "1/13/22"

In [24]:
size(datos)

(280, 727)

In [25]:
first(datos,5)

5×727 DataFrame. Omitted printing of 722 columns
│ Row │ Province/State │ Country/Region │ Lat      │ Long     │ 1/22/20 │
│     │ String?        │ String         │ Float64? │ Float64? │ Int64   │
├─────┼────────────────┼────────────────┼──────────┼──────────┼─────────┤
│ 1   │ missing        │ Afghanistan    │ 33.9391  │ 67.71    │ 0       │
│ 2   │ missing        │ Albania        │ 41.1533  │ 20.1683  │ 0       │
│ 3   │ missing        │ Algeria        │ 28.0339  │ 1.6596   │ 0       │
│ 4   │ missing        │ Andorra        │ 42.5063  │ 1.5218   │ 0       │
│ 5   │ missing        │ Angola         │ -11.2027 │ 17.8739  │ 0       │

In [26]:
rename!(datos, 1 => "Provincia", 2 => "País", 3 => "Latitud", 4 => "Longitud");
# datos1 = rename(.....)

In [27]:
last(datos,5)

5×727 DataFrame. Omitted printing of 722 columns
│ Row │ Provincia │ País               │ Latitud  │ Longitud │ 1/22/20 │
│     │ String?   │ String             │ Float64? │ Float64? │ Int64   │
├─────┼───────────┼────────────────────┼──────────┼──────────┼─────────┤
│ 1   │ missing   │ Vietnam            │ 14.0583  │ 108.277  │ 0       │
│ 2   │ missing   │ West Bank and Gaza │ 31.9522  │ 35.2332  │ 0       │
│ 3   │ missing   │ Yemen              │ 15.5527  │ 48.5164  │ 0       │
│ 4   │ missing   │ Zambia             │ -13.1339 │ 27.8493  │ 0       │
│ 5   │ missing   │ Zimbabwe           │ -19.0154 │ 29.1549  │ 0       │

In [28]:
datos[]

LoadError: MethodError: no method matching getindex(::DataFrame)
Closest candidates are:
  getindex(::AbstractDataFrame, ::CartesianIndex{2}) at /Users/carloslesmes/.julia/packages/DataFrames/GtZ1l/src/other/broadcasting.jl:3
  getindex(::DataFrame, ::Union{Regex, AbstractVector{T} where T, InvertedIndex}) at deprecated.jl:70
  getindex(::DataFrame, ::Union{AbstractString, Signed, Symbol, Unsigned}) at deprecated.jl:70
  ...

In [ ]:
paises = datos[:,"País"] 

In [ ]:
paises1 = datos[:,:País]

In [ ]:
unique(paises1)

In [ ]:
paises2 = datos[:,2]

In [ ]:
fila = findfirst(==("Colombia"), paises)

In [ ]:
datos_Col = filter( x -> x.País == "Colombia", datos)

In [ ]:
using Plots

In [ ]:
datos_COL = Vector(datos_Col[1, 5:end])

In [ ]:
scatter(datos_COL)

## El paquete RCall

Este paquete permite "correr" R desde la consola de julia. Para empezar active el paquete y entre `$`. Para salir de R haga backspace. En jupyter cambie el kernel, previamente debe instalar en R el paquete `IRkernel`. 

### Paquetes Estadísticos

El paquete `StatsKit`es un meta-paquete que carga paquetes esenciales de Estadística. [StatsKit](https://github.com/JuliaStats/StatsKit.jl). Para personas que trabajan con Estadística y quieren cargarlos en una sola llamada.

In [ ]:
using StatsKit

In [ ]:
using StatsBase

In [ ]:
names(StatsBase)

In [ ]:
?mean

In [ ]:
using StatsBase

In [ ]:
?winsor

## Paquete Distributions

In [ ]:
]add Distributions

In [ ]:
using Distributions

## Paquete PrettyTables

In [ ]:
]add PrettyTables

In [ ]:
using PrettyTables

In [ ]:
data = rand(100,10); pretty_table(data, highlighters = (hl_gt(0.5),))

## Paquete HypothesisTests

[HypothesisTests](https://juliastats.org/HypothesisTests.jl/stable/)

In [ ]:
]add HypothesisTests

In [ ]:
using HypothesisTests

In [ ]:
x=rand(Normal(),1000);

In [ ]:
t1=OneSampleTTest(x)

In [ ]:
pvalue(t1)

In [ ]:
ic = confint(t1, level = 0.95, tail = :both)

## Paquete GLM

## Paquete ScikitLearn

[SciKitLearn](https://cstjean.github.io/ScikitLearn.jl/dev/)

## Paquete Flux

[Flux](https://fluxml.ai/Flux.jl/stable/models/basics/)

# Modulos

In [ ]:
module Sturges
    export clases
    function clases(n)
    clases = 1.0 + 3.3 * log10(n)
    println("Número de clases => ", clases)
    end
end

In [ ]:
Sturges.clases(1000)